#!/usr/bin/env python3
"""
Migration Script: Restructure GAN Run Folders.

This script migrates existing artifacts from the flat structure:
    v1/run/gan/0002_horses/
    ├── analysis_report.md
    ├── critic.keras
    ├── images/
    └── ...

To the new run-based structure:
    v1/run/gan/0002_horses/005/
    ├── 005_analysis_report.md
    ├── critic.keras
    ├── images/
    └── ...

Usage:
    uv run python scripts/migrate_run_folders.py

Notes:
    - Source files are COPIED, not moved, for safety.
    - After verifying the migration, manually delete source files.
    - The analysis_report.md is renamed with experiment ID prefix.

Author:
    Auto-generated by AI assistant.
"""

import os
import shutil
from pathlib import Path


# =============================================================================
# MIGRATION CONFIGURATION
# =============================================================================
# Adjust these values for your specific migration needs.
# =============================================================================

# Source folder containing the flat structure
SOURCE_FOLDER = Path("v1/run/gan/0002_horses")

# Target experiment run ID (should match Master Experiment Log)
TARGET_RUN_ID = "005"


# =============================================================================
# ITEMS TO MIGRATE
# =============================================================================
# List of files and directories to migrate from flat structure.
# Items not present in source folder are silently skipped.
# =============================================================================

ITEMS_TO_MIGRATE = [
    "analysis_report.md",
    "critic.keras",
    "generator.keras",
    "model.keras",
    "obj.pkl",
    "params.pkl",
    "wassersteinloss_vs_batch.png",
    "images",
    "viz",
    "weights",
]


def migrate():
    """
    Migrate existing files from flat structure to run-specific folder.

    Creates the target folder structure and copies all specified items.
    The analysis_report.md file is renamed with the experiment run ID prefix.

    Returns:
        None

    Raises:
        FileNotFoundError: If source folder does not exist.
    """
    # Validate source folder exists
    if not SOURCE_FOLDER.exists():
        raise FileNotFoundError(f"Source folder not found: {SOURCE_FOLDER}")

    # Create target folder path
    target_folder = SOURCE_FOLDER / TARGET_RUN_ID

    # Create target folder
    target_folder.mkdir(parents=True, exist_ok=True)
    print(f"✓ Created target folder: {target_folder}")

    # Track migration statistics
    copied_files = 0
    copied_dirs = 0
    skipped_items = 0

    # Migrate each item
    for item in ITEMS_TO_MIGRATE:
        source = SOURCE_FOLDER / item

        if source.exists():
            dest = target_folder / item

            # Special case: rename analysis_report.md with experiment ID prefix
            if item == "analysis_report.md":
                dest = target_folder / f"{TARGET_RUN_ID}_analysis_report.md"

            # Handle directories
            if source.is_dir():
                # Remove existing destination directory if present
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(source, dest)
                copied_dirs += 1
                print(f"  ✓ Copied directory: {item} → {dest.name}/")

            # Handle files
            else:
                shutil.copy2(source, dest)
                copied_files += 1
                print(f"  ✓ Copied file: {item} → {dest.name}")
        else:
            skipped_items += 1
            print(f"  ⚠ Skipped (not found): {item}")

    # Print summary
    print(f"\n{'=' * 50}")
    print("MIGRATION SUMMARY")
    print(f"{'=' * 50}")
    print(f"  Files copied:       {copied_files}")
    print(f"  Directories copied: {copied_dirs}")
    print(f"  Items skipped:      {skipped_items}")
    print(f"{'=' * 50}")
    print(f"\n✓ Migration complete!")
    print(f"  Source files remain in: {SOURCE_FOLDER}")
    print(f"  Migrated to:            {target_folder}")
    print("\n  ⚠ IMPORTANT: After verifying the migration, manually delete")
    print("    the original files from the source folder.")


if __name__ == "__main__":
    migrate()
